[package]
name = "zgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "24.0.1"
winit = "0.30.9"
glm = "0.2.3"
image = "0.25.5"
font = "0.40.0"
imgui = "0.12.0"
ttf-parser = "0.25.1"
toml = "0.8.23"
serde = { version = "1.0.219", features = ["derive"] }
